### ISSUE TITLE
Seaglass Demo not working with Jre 1.7

### ISSUE THREAD

**Issue by GoogleCodeExporter** [khuxtable/seaglass#99]
```
What steps will reproduce the problem?
1. Run the demo in java 1.7
2. Exception in thread "main" java.lang.NoClassDefFoundError: 
sun/swing/plaf/synth/SynthUI


What is the expected output? What do you see instead?
Should work without any error.
getting Exception in thread "main" java.lang.NoClassDefFoundError: 
sun/swing/plaf/synth/SynthUI

What version of the product are you using? On what operating system? What
JRE version?

Java 1.7

Please provide any additional information below.

```

Original issue reported on code.google.com by `vargh...@gmail.com` on 26 Feb 2013 at 6:32
